// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLog(arg1) {
  return window['go']['main']['App']['ClearLog'](arg1);
}

export function Extract(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['Extract'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PreviewMatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewMatch'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function Undo(arg1) {
  return window['go']['main']['App']['Undo'](arg1);
}
