// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {extract} from '../models';

export function ClearLog(arg1:string):Promise<main.ClearLogResult>;

export function Extract(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean,arg8:boolean):Promise<extract.ExtractResult>;

export function GetFileStats(arg1:string):Promise<main.FileStats>;

export function GetLog(arg1:string):Promise<extract.LogResult>;

export function Greet(arg1:string):Promise<string>;

export function PreviewMatch(arg1:string,arg2:string,arg3:string):Promise<extract.PreviewResult>;

export function SelectDirectory():Promise<string>;

export function Undo(arg1:string):Promise<main.UndoResult>;
